# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /code

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /code

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /code/CMakeFiles /code/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /code/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ghttpd

# Build rule for target.
ghttpd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ghttpd
.PHONY : ghttpd

# fast build rule for target.
ghttpd/fast:
	$(MAKE) -f CMakeFiles/ghttpd.dir/build.make CMakeFiles/ghttpd.dir/build
.PHONY : ghttpd/fast

src/ghttpd_core.o: src/ghttpd_core.cpp.o
.PHONY : src/ghttpd_core.o

# target to build an object file
src/ghttpd_core.cpp.o:
	$(MAKE) -f CMakeFiles/ghttpd.dir/build.make CMakeFiles/ghttpd.dir/src/ghttpd_core.cpp.o
.PHONY : src/ghttpd_core.cpp.o

src/ghttpd_core.i: src/ghttpd_core.cpp.i
.PHONY : src/ghttpd_core.i

# target to preprocess a source file
src/ghttpd_core.cpp.i:
	$(MAKE) -f CMakeFiles/ghttpd.dir/build.make CMakeFiles/ghttpd.dir/src/ghttpd_core.cpp.i
.PHONY : src/ghttpd_core.cpp.i

src/ghttpd_core.s: src/ghttpd_core.cpp.s
.PHONY : src/ghttpd_core.s

# target to generate assembly for a file
src/ghttpd_core.cpp.s:
	$(MAKE) -f CMakeFiles/ghttpd.dir/build.make CMakeFiles/ghttpd.dir/src/ghttpd_core.cpp.s
.PHONY : src/ghttpd_core.cpp.s

src/ghttpd_event.o: src/ghttpd_event.cpp.o
.PHONY : src/ghttpd_event.o

# target to build an object file
src/ghttpd_event.cpp.o:
	$(MAKE) -f CMakeFiles/ghttpd.dir/build.make CMakeFiles/ghttpd.dir/src/ghttpd_event.cpp.o
.PHONY : src/ghttpd_event.cpp.o

src/ghttpd_event.i: src/ghttpd_event.cpp.i
.PHONY : src/ghttpd_event.i

# target to preprocess a source file
src/ghttpd_event.cpp.i:
	$(MAKE) -f CMakeFiles/ghttpd.dir/build.make CMakeFiles/ghttpd.dir/src/ghttpd_event.cpp.i
.PHONY : src/ghttpd_event.cpp.i

src/ghttpd_event.s: src/ghttpd_event.cpp.s
.PHONY : src/ghttpd_event.s

# target to generate assembly for a file
src/ghttpd_event.cpp.s:
	$(MAKE) -f CMakeFiles/ghttpd.dir/build.make CMakeFiles/ghttpd.dir/src/ghttpd_event.cpp.s
.PHONY : src/ghttpd_event.cpp.s

src/ghttpd_httpd.o: src/ghttpd_httpd.cpp.o
.PHONY : src/ghttpd_httpd.o

# target to build an object file
src/ghttpd_httpd.cpp.o:
	$(MAKE) -f CMakeFiles/ghttpd.dir/build.make CMakeFiles/ghttpd.dir/src/ghttpd_httpd.cpp.o
.PHONY : src/ghttpd_httpd.cpp.o

src/ghttpd_httpd.i: src/ghttpd_httpd.cpp.i
.PHONY : src/ghttpd_httpd.i

# target to preprocess a source file
src/ghttpd_httpd.cpp.i:
	$(MAKE) -f CMakeFiles/ghttpd.dir/build.make CMakeFiles/ghttpd.dir/src/ghttpd_httpd.cpp.i
.PHONY : src/ghttpd_httpd.cpp.i

src/ghttpd_httpd.s: src/ghttpd_httpd.cpp.s
.PHONY : src/ghttpd_httpd.s

# target to generate assembly for a file
src/ghttpd_httpd.cpp.s:
	$(MAKE) -f CMakeFiles/ghttpd.dir/build.make CMakeFiles/ghttpd.dir/src/ghttpd_httpd.cpp.s
.PHONY : src/ghttpd_httpd.cpp.s

src/ghttpd_shedule.o: src/ghttpd_shedule.cpp.o
.PHONY : src/ghttpd_shedule.o

# target to build an object file
src/ghttpd_shedule.cpp.o:
	$(MAKE) -f CMakeFiles/ghttpd.dir/build.make CMakeFiles/ghttpd.dir/src/ghttpd_shedule.cpp.o
.PHONY : src/ghttpd_shedule.cpp.o

src/ghttpd_shedule.i: src/ghttpd_shedule.cpp.i
.PHONY : src/ghttpd_shedule.i

# target to preprocess a source file
src/ghttpd_shedule.cpp.i:
	$(MAKE) -f CMakeFiles/ghttpd.dir/build.make CMakeFiles/ghttpd.dir/src/ghttpd_shedule.cpp.i
.PHONY : src/ghttpd_shedule.cpp.i

src/ghttpd_shedule.s: src/ghttpd_shedule.cpp.s
.PHONY : src/ghttpd_shedule.s

# target to generate assembly for a file
src/ghttpd_shedule.cpp.s:
	$(MAKE) -f CMakeFiles/ghttpd.dir/build.make CMakeFiles/ghttpd.dir/src/ghttpd_shedule.cpp.s
.PHONY : src/ghttpd_shedule.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... ghttpd"
	@echo "... rebuild_cache"
	@echo "... src/ghttpd_core.o"
	@echo "... src/ghttpd_core.i"
	@echo "... src/ghttpd_core.s"
	@echo "... src/ghttpd_event.o"
	@echo "... src/ghttpd_event.i"
	@echo "... src/ghttpd_event.s"
	@echo "... src/ghttpd_httpd.o"
	@echo "... src/ghttpd_httpd.i"
	@echo "... src/ghttpd_httpd.s"
	@echo "... src/ghttpd_shedule.o"
	@echo "... src/ghttpd_shedule.i"
	@echo "... src/ghttpd_shedule.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

